"""Generate STATUS.md's known-broken table from the reproducers.

    python -m tools.status_table          # print it
    python -m tools.status_table --check  # non-zero if STATUS disagrees

The table used to be written by hand and roughly a quarter of its rows were
wrong — `F1`-`F4` sat marked CRITICAL for four phases after being closed. The
rows that can be reproduced now come from `tests/known_broken.py`, where an
`xfail(strict=True)` fails CI the moment the problem is fixed.

It prints the un-policed rows too, and says so. A generator that quietly emitted
only what it could check would be a nicer-looking version of the same rot.
"""

from __future__ import annotations

import argparse
import importlib
import inspect

MODULE = "tests.known_broken"
HEADER = "| Problem | Reproducer | State |\n|---|---|---|"


def rows() -> list[tuple[str, str, str]]:
    module = importlib.import_module(MODULE)
    out: list[tuple[str, str, str]] = []
    for name, fn in sorted(vars(module).items()):
        if not (name.startswith("test_") and inspect.isfunction(fn)):
            continue
        for mark in getattr(fn, "pytestmark", []):
            if mark.name == "xfail":
                reason = " ".join(str(mark.kwargs.get("reason", "")).split())
                out.append((reason, f"`{name}`", "**open**"))
    return out


def render() -> str:
    lines = [
        "<!-- generated by `make status-table`. Do not hand-edit the rows below. -->",
        "",
        HEADER,
    ]
    lines += [f"| {why} | {where} | {state} |" for why, where, state in rows()]
    lines += [
        "",
        f"_{len(rows())} reproducible "
        f"{'problem, an' if len(rows()) == 1 else 'problems, each an'} "
        "`xfail(strict=True)` in "
        f"`{MODULE.replace('.', '/')}.py`. Fixing one turns it into an XPASS, which "
        "fails the suite and forces the row out — a fix cannot land unnoticed._",
        "",
        "**Not policed by this table.** Problems with no minimal reproducer stay "
        "prose below and stay unchecked: toy scale, one model and one prompt, "
        "single-sample timing, defect rates unvalidated against production formats, "
        "and every audit being one person auditing their own design. Naming them "
        "here is the only guard they have.",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="tools.status_table")
    ap.add_argument("--check", action="store_true", help="non-zero if STATUS is stale")
    args = ap.parse_args(argv)
    table = render()
    if not args.check:
        print(table)
        return 0

    from pathlib import Path

    status = Path("STATUS.md").read_text(encoding="utf-8")
    missing = [why for why, _, _ in rows() if why.split(":")[0] not in status]
    if missing:
        print("STATUS.md is missing reproducible problems:")
        for why in missing:
            print(f"  - {why[:90]}")
        return 1
    print(f"STATUS.md accounts for all {len(rows())} reproducible problems.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
